version: '2'

services:
    app:
        build: docker/app
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            APP_APACHE_ROOT_DIR: /var/www/html
        ports:
            - 82:80
    db:
        image: mysql:5.6
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: presta-doc-bot
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        volumes:
            - db:/var/lib/mysql
    node:
        image: node:10.16
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            PATH: /var/www/html/node_modules/.bin/:$PATH
volumes:
  db: {}